version: 2
jobs:
  macOS_swift_5.1:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test
      - run:
          name: Build Spec Fixtures
          command: ./build_specs.sh
      - run:
          name: Build Release
          command: make build
workflows:
  version: 2
  workflow:
    jobs:
      - macOS_swift_5.1
